name: Build Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STACK_VERSION: 7.17.0
    steps:
      - uses: actions/checkout@master

      - name: Log in to the GHCR
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up image name
        run: |
          GHRC_IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}:${{ env.STACK_VERSION }}" | tr '[:upper:]' '[:lower:]')
          GHRC_IMAGE_NAME_LATEST=$(echo "ghcr.io/${{ github.repository }}:latest" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=GHRC_IMAGE_NAME::$GHRC_IMAGE_NAME"
          echo "::set-output name=GHRC_IMAGE_NAME_LATEST::$GHRC_IMAGE_NAME_LATEST"
        id: image-name

      - name: Build image And Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: STACK_VERSION=${{ env.STACK_VERSION }}
          add_git_labels: true
          tags: |
            ${{ steps.image-name.outputs.GHRC_IMAGE_NAME }}
            ${{ steps.image-name.outputs.GHRC_IMAGE_NAME_LATEST }}

